sudo: required
dist: trusty
language: python
python:
  - "3.5"
install:
  - pip install numpy
  - pip install matplotlib
  - pip install scipy
  - pip install scikit-learn
  - pip install tensorflow
script: py.test
notifications:
  email: false
